### ISSUE TITLE
RETOCAR ARCHIVO DE IMAGEN

### ISSUE THREAD

**Issue by ACCA777** [ACCA777/examenantonioceniza#1]
QUIERO QUIERO QUE  AL PATO LUCAS SE LE AGREGE POR PHOTOSHOP UN GORRITO CON HELICÓPTERO Y LE CAMBIES LOS COLORES , EL GORRITO QUE SE ENCARGUE DIEGO QUE ES EL ESPECIALISTA Y CRISTINA QUE LE CAMBIE EL COLOR

**Comment by ACCA777** [comment]
QUIERO QUE DIEGO LE PONGAS EL GORRITO

**Comment by ClaseRedes** [comment]
Pero primero me lo tienes que comprar a mí xDDD
